### ISSUE TITLE
Beim Löschen eines Blocks gehen alle folgenden verloren

### ISSUE THREAD

**Issue by thetathaurus** [thetathaurus/storylike#106]
Beim Löschen eines Blocks innerhalb eines Nodes gehen alle folgenden verloren.

**Comment by Executer84** [comment]
Hallo auch von mir: Mit dem Löschen stimmt derzeit generell noch einiges nicht! Ich habe in meiner Emustory den vorletzten Block gelöscht und wie du schon schreibst wurden bei mir dadurch zunächst die letzten beiden Blöcke gelöscht. Als ich anschließend aber meine Story erneut geöffnet habe ist das kompletter Salat und ich habe nur noch den letzten Block angezeigt. Da musst du nochmal ran.

Schritt 1: Löschen von "Block 3" meiner Story
![image](https://user-images.githubusercontent.com/46623291/51832574-59c62300-22f5-11e9-9708-074089bd225b.png)
Schritt 2: Jetzt ist "Block 3" und "Ende" gelöscht
![image](https://user-images.githubusercontent.com/46623291/51832596-6a769900-22f5-11e9-81d0-445c44a2a716.png)
Schritt 3: Ich öffne erneut meine Story und jetzt habe ich nur noch "Ende". Wo ist "Beginn" bis "Block 2" hin??
![image](https://user-images.githubusercontent.com/46623291/51832687-a578cc80-22f5-11e9-95cd-cb38d0c4aadf.png)

**Comment by thetathaurus** [comment]
Fehler ist behoben. Alle notwendigen Links (auch bei mehreren Parents und Childs werden erzeugt, falls der Storyblock der letzte des Knotens war
