### ISSUE TITLE
Wiki - Registerkarte löschen funktioniert nicht

### ISSUE THREAD

**Issue by Executer84** [thetathaurus/storylike#107]
Habe eine neue Wiki "Natur - Laufvögel" angelegt. Darin ein erstes Register "Emus". Wollte dieses Register wieder löschen per "Delete" -> Sicherheitsabfrage sehr gut :-) 
Aber: Nachdem ich das Sicherheitswort eingetippt habe wird "Delete" grün und ich kann das Register scheinbar löschen. Wird dann auch zunächst nicht mehr angezeigt. Öffne ich jedoch erneut die Wiki dann ist das wieder da! Verbuggt? Es ist mir jedenfalls nicht gelungen die Registerkarte dauerhaft zu löschen.

**Comment by thetathaurus** [comment]
Du warst er Erste der es überhaupt probiert hat.... vor mir... Es war noch nicht mal implementiert. Funktioniert jetzt.
