### ISSUE TITLE
ohne "www." geht's nicht?

### ISSUE THREAD

**Issue by Executer84** [thetathaurus/storylike#109]
Als Hinweis: Wenn man das "www." nicht mit eintippt wird storylike vom browser nicht gefunden (zumindest nicht bei der ersten Anwahl, oder wenn man wie ich keine Cookies zulässt). Mit der Eingabe "storylike.com" wird bei mir in Edge https://storylike.com gesucht und das gibt eine Fehlermeldung.
Kenne mich mit sowas nicht aus und kann nicht sagen, ob man da was machen kann. Jedenfalls lasse ich das www. inzwischen so gut wie immer weg und das klappt bei allen anderen Webseiten.
![image](https://user-images.githubusercontent.com/46623291/51832017-dce67980-22f3-11e9-8eb2-1c759fde31dc.png)

**Comment by thetathaurus** [comment]
Ist tatsächlich ein Fehler, der aufgrund einer temporären Umstrukturierung
Auftritt. Danke fürs dokumentieren!
Wird umgehend behoben

Am Mo., 28. Jan. 2019, 12:00 hat Executer84 <notifications@github.com>
geschrieben:

**Comment by thetathaurus** [comment]
Fehler ist behoben
