### ISSUE TITLE
Map: Punktedetails

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#11]
"Wenn ich die Map aufmache, würde ich gern auf einen Punkt nur hovern müssen, um die Vorschau zu sehen.
Stattdessen muss ich klicken. "

**Comment by thetathaurus** [comment]
ist ein gutes Feature Request  - wird implementiert

**Comment by thetathaurus** [comment]
Ist aus Komplexitätsgründen und Kompabilitätsgründen mit der mobilen Benutzung leider nicht ohne sehr großen Implementierungsaufwand machbar.
