### ISSUE TITLE
Benutzerfreundlichkeit - Menuführung verbessern

### ISSUE THREAD

**Issue by Executer84** [thetathaurus/storylike#110]
Hinweis zur Benutzerfreundlichkeit: Die Menuführung finde ich derzeit nicht optimal gelungen.

1. Beispiel: Im Startmenu klicke ich auf "Stories" und da wird mir alles angezeigt... nur nicht meine eigenen unveröffentlichten Stories. Wenn ich an meine eigenen Stories rankommen will, dann geht das derzeit nur über das doch recht unscheinbare "Projects - Show all". Außerdem habe ich auf der Startseite gleich zweimal die Schaltfläche "add new Story", einmal unter "Projects" und einmal im Startmenu. Zuletzt habe ich noch einen Schnellbutton um an jeder meiner aktuellen Stories weiterzuschreiben. Die Schnellbuttons finde ich ganz gut aber der Rest?

2. Beispiel: Wie, was und Wo finde ich derzeit alles Infos über mich als Autor und mich als User? Es gibt im Startmenu den Punkt "Settings", da komme ich aber erstmal nur an meine Userdaten ran. Um an mich und meine Autoren ranzukommen muss ich dann erst mühsam unter Settings "manage my authors" anklicken. Auf der Startseite habe ich keinen Link der mich zu meiner persönlichen Seite / zu meinen Autoren bringt. Warum gibt es nicht generell einen Hauptmenu-Punkt "my profile" unter dem mir dann alles angezeigt wird: Mein Profil, meine Autoren und meine Userdaten?

Meine Empfehlung: Menuführung klarer Gestalten und auf der Startseite prominenter und eindeutiger darstellen. Für mich sind "my stories" und "my profile" zwei prominente Punkte, die einfach erklärt auf die Startseite gehören.

**Comment by thetathaurus** [comment]
Wurde bereits stark dran gearbeitet, ist nur noch nicht freigegeben.
Änderungen: -> Es gibt jetzt ein horizontales Menu für "Stories", "Wiki", "Notifications" und dem "Account". Unter "Account" befinden sich ausschließlich nutzerspezifische Info's wie "Profil", "Autoren" sowie ein Link zum persönlichen "Dashboard". Letzteres ist auch über den klick auf das Logo erreichbar.
Damit sollte dem Punkt 2 entsprochen sein. 
Im Handy-Display Modus werden die Menu's aus Platzgründen zusammengelegt.

Das Dashboard wurde verschlankt und die Namen einheitlich gemacht. Ich werden den Button "Show All" mehr präsent machen. Die Startseite benötigt darüber hinaus noch mehr erklärenden Text den ich hinzufügen werde

**Comment by thetathaurus** [comment]
Die neue Menüführung ist verfügbar. Bitte einmal ausprobieren
![image](https://user-images.githubusercontent.com/4700713/51890900-c09f1700-239d-11e9-8f09-67462ba502b6.png)

**Comment by Executer84** [comment]
Hi! Erstes Feedback: Die Menuführung gefällt mir jetzt schon deutlich besser! Ist für mich sehr viel geordneter und damit auch eingängiger. Auch die "Show all" Schaltflächen sind jetzt besser optisch hervorgehoben.
Zwei Dinge, die mir schon länger aufgefallen sind:

1. Ich wünsche mir einen "Home" Button um zurück zur Startseite zu kommen. Ja, ich weiß, man kann links oben auf das Storylike-Symbol klicken, dass ist aber nicht unbedingt für jeden DAU gleich erkennbar. Homebutton z.B. rechts oben im Menu einbauen?

2. Ich wünsch mir in den Untermenus eine "zurück zur nächsthöheren Ebene" bzw. eine "zurück zur vorherigen Seite" Schaltfläche. Beispiel: Gehe ich auf "My Projects - Show all" bekomme ich das schöne Untermenu mit allen meinen Projekten. Klicke ich jetzt z.B. ein einzelnes Buch oder einen Autor an kann ich anschließend nicht bequem und einfach zurück auf meine Projektübersicht. Ich kann das derzeit nur über den "Pfeil zurück" in meinem Browser, oder ich muss mich mühsam wieder vom Startmenu aus vorarbeiten. Ich kann mir vorstellen, dass ist nicht ganz so einfach zu programmieren, macht es mir als dummen/faulen User aber einfacher.

**Comment by thetathaurus** [comment]
Ich habe den Home-Button hinzugefügt. Hatte ihn eigentlich wieder rausgenommen, aber tatsächlich ist Alpha-Testing schon etwas wie "Wünsch-dir-was"

Bezüglich der Frage "Zurück zur nächsthöheren Ebene", die sogenannt e Breadcrumb-Navigation habe ich aktuell bewusst noch nicht eingebaut und existiert bereits als weiteres Ticket. Es ist deswegen nicht trivial zu implementieren, da eine Story nicht einer Ebene, sondern mehren untergeordnet sind (z.B. Lese-Bookmarks, Catalog, Meine Projekte,.....) 

Ich schließe damit den Issue.
