### ISSUE TITLE
"My Stories" - Autor anklicken falsch verlinkt

### ISSUE THREAD

**Issue by Executer84** [thetathaurus/storylike#111]
Unter "my stories" und "my contributions" werden alle meine Geschichten aufgelistet. Wenn ich bei einer der Geschichten auf den Autor klicke, werde ich nicht zum Autor weitergeleitet sondern zur Geschichte. Falsche Verlinkung.
Ich würde übrigens auch auf die Seite des Autors verlinken, wenn ich auf das Profilbild des Autors klicke. Derzeit komme ich überall nur zur Geschichte "Awesome Emu Story"...
![image](https://user-images.githubusercontent.com/46623291/51835601-3d7ab400-22fe-11e9-8dc4-c481c3dc5c52.png)

**Comment by thetathaurus** [comment]
fixed in next release
