### ISSUE TITLE
Mapping derzeit broken

### ISSUE THREAD

**Issue by Executer84** [thetathaurus/storylike#112]
Du arbeitest derzeit viel im Bereich "Text editieren". Dadurch scheint jetzt das Mapping verbuggt zu sein, das klappt in meiner Emu-Story gar nicht mehr, es wird beim Schreiben eines neuen Blocks kein neuer Eintrag mehr aufgenommen. Bei bestehenden Geschichten kann ich das noch anwählen.

**Comment by thetathaurus** [comment]
Mögliche Probleme wurden behoben.
