### ISSUE TITLE
Access level einstellen - Personen sind vorausgefüllt

### ISSUE THREAD

**Issue by Executer84** [thetathaurus/storylike#113]
Wenn ich eine neue Geschichte starte und das Access-Level ändern möchte sind da bereits Personen vorausgewählt. Ich nehme an, dass sind die Personen/Autoren, die ich beim letzten Mal freigeschaltet habe. Ist das so gewollt? Ich kann mir vorstellen, dass wird auf Dauer recht unübersichtlich, je häufiger ich Access-Level freischalte. Kann man natürlich so machen, aber mir persönlich wäre es lieber, erstmal mit einer leeren Liste zu starten. Nicht, dass ich versehentlich meine Oma für meine amourösen Fetisch-Geschichten mit meiner Internet-Liebe freischalte...

![image](https://user-images.githubusercontent.com/46623291/51909188-476ae880-23cc-11e9-8d01-e9ff556ee18e.png)

**Comment by thetathaurus** [comment]
War ein Fehler. Das initiale Set war aus versehen noch von der vorherigen geöffneten Adresse gesetzt. In diesem Falle wohl "Kriegszug nach Normont". Ist gelöst
