### ISSUE TITLE
Kann derzeit keine neue Geschichte starten

### ISSUE THREAD

**Issue by Executer84** [thetathaurus/storylike#114]
Ähnlich wie beim Mapping, da ist jetzt wohl bei den Änderungen einiges zu Bruch gegangen: Ich kann derzeit keine neue Geschichte starten. Klicke ich im Deckblatt unten auf Save passiert nichts.

**Comment by thetathaurus** [comment]
Problem wurde behoben. Danke für das schnelle prüfen.
