### ISSUE TITLE
Access Level - nur Suche und Freischalten von Usern möglich, nicht von Autoren

### ISSUE THREAD

**Issue by Executer84** [thetathaurus/storylike#115]
Als Idee für zusätzliches Feature: Man kann derzeit nur Usernamen suchen und freischalten, nicht deren einzelne Autoren. 

Immerhin: Dafür kann ich mir derzeit selbst Rechte freischalten :-)

**Comment by thetathaurus** [comment]
Dass man nur Accounts suchen und freigeben kann ist gewollt. 
Ich habe einen zusätzlichen Filter eingefügt, damit man sich nicht selbst hinzufügen kann.
