### ISSUE TITLE
Ganz allgemein: Usernamen und Autorennamen mehrfach vergeben?

### ISSUE THREAD

**Issue by Executer84** [thetathaurus/storylike#116]
Nur falls du dir dazu nicht bereits Gedanken gemacht hast: Je größer deine Plattform wird desto eher wird es zu Usernamen-Doppelungen und Autorennamen-Doppelungen kommen. Du brauchst ein Konzept, wie du damit umgehen willst:
Usernamen-Mehrfachnennung zulassen Ja oder Nein?
Autorennamen-Mehrfachnennung wirst du wohl nur mit Ja beantworten können. 
Dieses Thema hat Einfluss auf ne ganze Menge Bereiche, z.B. die Suchfunktion. Oder für kommerziell schreibende Autoren. Ich möchte mir dann gerne schonmal die Usernamen "Wolfgang Holbein", "Stephen King" und "Joanne K. Rowling" reservieren. Danke!

P.s. Das musst du natürlich alles auch rechtlich absichern, im Disclaimer. Aber daran hast du sicher bereits gedacht.
P.p.s: Den Usernamen Donald Trump kannst du behalten. Der braucht aber auch nur Blöcke mit 280 Zeichen...

**Comment by thetathaurus** [comment]
Usernamen und Authorennamen können doppelt vergeben werden.
Es ist geplant für "Bekannte Personen", oder jene die dies möchten ein "Verify"- Symbol einzublenden, und ggf anderen User dann die Möglichkeit geben einen anderen usernamen zu nutzen. Da wir mehrere social Media Identity-Provider (Google, Faceboook mindestens) nutzen, haben wir gar nicht die Hoheit über die Usernamen. Ich packe die Frage auf Review, allein wegen dem Kommtar zum Trump ;-)
