### ISSUE TITLE
initiale Vorbelegung bei Wiki-Auswahl / keine Wiki-Auswahl möglich bei "start new story"

### ISSUE THREAD

**Issue by Executer84** [thetathaurus/storylike#117]
Auch bei der Wiki-Auswahl im Header einer Geschichte scheint es eine initiale Vorbelegung zu geben. Darin wird meine später eingerichtete Wiki Laufvögel nicht aufgeführt. Ich kann die aber immerhin suchen und dann auswählen. Vorbelegung überarbeiten?
![image](https://user-images.githubusercontent.com/46623291/52049086-28479480-254d-11e9-8829-c5ce1f068304.png)

**Comment by Executer84** [comment]
Nachtrag: Das die Wiki vorbelegt war hatte ich jetzt nur bei meiner alten, bereits existierenden Geschichte. Als ich eine neue Story beginnen wollte, hat die Wiki-Auswahl gar nicht geklappt. Ich konnte initial keine Wiki importieren. Allerdings: Kaum hatte ich die neue Story einmal abgespeichert und mit Edit den Header erneut geöffnet, konnte ich eine Wiki importieren! (auch hier war dann wieder die initiale Vorbelegung von oben, ohne "Laufvögel")
There is something broken, I guess.

**Comment by thetathaurus** [comment]
Korrigiert. War eine fehlerhafter implementierung
