### ISSUE TITLE
Autorenlinie bei "How to continue?" kenntlich machen

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#12]
"Bei Blockende, ""How to continue?"", wäre es super, die Autorenlinie kenntlich zu haben. Vor allem, da es 
vorkommen kann, dass mehrere Autoren dieselbe Farbe haben. "

**Comment by thetathaurus** [comment]
Die Autorenlinie ist stets der 1. Eintrag. Danach kommen absteigend die
"besten" Möglichkeiten

Stories haben 2 Modi die der Story-Owner festlegt
1) Verlange eine Entscheidung. Hier werden alle Optionen aufgelistet (die
1. ist die Autorenlinie)
oder
2) folge der Autorenlinie. Bei diesem Modus wird die Autorenlinie
automatisch weitergeführt / geladen und die Optionen werden zusätzlich
angezeigt.

Würde es helfen den Namen des Autoren vor dem Titel zu haben?
