### ISSUE TITLE
Clapping-Removal

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#14]
"Ich kann 10mal klatschen, aber wenn ich das dann rückgängig mache, sind direkt alle 10 weg. Ich kann also, 
wenn ich einmal zuviel clappe, wieder von vorne loslegen. "

**Comment by thetathaurus** [comment]
Würdest du eher erwarten, dass es bei einem Rücknopf -1 Claps gibt? Der
Knopf ist derzeit eher als ein "Reset" gedacht.
Da man den sehr schnell clappen kann, sind die 7 "Claps" schnell wieder
gesetzt.
Bei -1 müsste ich den kleinen Knopf sehr häufig treffen um ggf auf 0 zu
kommen.

**Comment by boxerfred** [comment]
Hm. Intuitiv würde ich -1 erwarten, aber ich würde das nicht als Expertenmeinung werten. Mach, wie du's für richtig hältst.
