### ISSUE TITLE
Screen-Größe bei Kommentaren

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#15]
Die Kommentare nehmen mit 50% des Screens IMHO zuviel Platz weg, aber musst du natürlich wissen

**Comment by thetathaurus** [comment]
Da sich Kommentare, die Map und der Context das gleiche Feld teilen, würde
ich dies so lassen.
Du kannst du Größe des rechten Felded mit dem "Grab-Control" ändern (Drag &
Move).
