### ISSUE TITLE
Was versteckt sich hinter "Next"? 

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#16]
"Wenn ich einen neuen Block verfasse, kann ich zwar auf ""Next"" klicken, aber das bringt mir so gar nichts.
Kommt da eine Funktionalität hinter? "

**Comment by thetathaurus** [comment]
Mit "Next" kannst du Steuern, welche Schlagworte / Verlinkungen genutzt
werden können und ggf Konflikte lösen, wenn einem Schlagwort mehrere
Register-Elemente zugeordnet werden.
