### ISSUE TITLE
Map: Verzweigungsrichtung

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#17]
"Wenn ich eine Map editiere und eine Linie von einem unteren Punkt zu einem höheren ziehe, kann ich kaum
erkennen, ob die Geschichte von mir nach oben führt oder von oben nach unten. Kann man ""Leserichtungen""
visualisieren?"

**Comment by thetathaurus** [comment]
Ausgehende Verbindungen fangen stets unterhalb eines Knoten an, eingehende
stets oberhalb.
Dies entspricht auch der Leserichtung. Es ist ein unterschied, ob du von
Punkt A nach Punkt B ziehst, oder umgekehrt.


Am Do., 22. Nov. 2018 um 17:56 Uhr schrieb boxerfred <
notifications@github.com>:

**Comment by boxerfred** [comment]
Das weiß ich. Aber es wirkt auf mich nicht intuitiv. Andererseits habe ich mich schon sehr bemüht, eine Unkenntlichkeit hervorzurufen. Vielleicht eher ein Thema für den Feinschliff?

**Comment by thetathaurus** [comment]
Zusätzliche Pfeilspitzen hatte ich damals versucht, jedoch war die zusätzliche Komplexität größer als der Nutzen. Aktuell würde ich das Thema nicht weiter verfolgen, es bleibt aber archiviert.
