### ISSUE TITLE
Story-Erstellung nicht möglich

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#18]
Ich kann nach wie vor keine eigene Geschichte anlegen. 

Ich klicke auf "New Story", füge Bild, Text und entsprechende Einstellungen (private, published) hinzu, drücke auf "Save", aber es geschieht nichts. 
<img width="1236" alt="screen shot 2018-11-22 at 21 26 54" src="https://user-images.githubusercontent.com/32750106/48921064-70876e00-ee9d-11e8-8e9f-79cd65c13ba9.png">
<img width="1221" alt="screen shot 2018-11-22 at 21 26 47" src="https://user-images.githubusercontent.com/32750106/48921065-70876e00-ee9d-11e8-92ad-d85e14e4b3d1.png">
![Uploading Screen Shot 2018-11-22 at 21.26.40.png…]()

**Comment by boxerfred** [comment]
Ohne Register geht es.

**Comment by boxerfred** [comment]
Wenn ich den Register im Nachhinein hinzufüge, geht es.

**Comment by thetathaurus** [comment]
Fehler ist bestätigt, wird behoben

**Comment by thetathaurus** [comment]
ist in Version 0.4.1 behoben
