### ISSUE TITLE
Story taucht mehrfach unter "Stories" auf?

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#20]
Jetzt wird's verrückt. Meine Geschichte taucht dreimal unter "Stories" auf: 

Ich gehe davon aus, dass da irgendwas gespeichert wurde, nachdem ich bei #18 mehrfach auf "Save" gedrückt habe. Oder so. 
<img width="1246" alt="screen shot 2018-11-22 at 21 32 36" src="https://user-images.githubusercontent.com/32750106/48921179-3c607d00-ee9e-11e8-9110-cf2c6a42af06.png">

**Comment by boxerfred** [comment]
Ich stelle fest: es sind verschiedene Stories, also wahrscheinlich erstellte Duplikate. Zumindest die Ids in der URL (345, 346) sind unterschiedlich.

**Comment by thetathaurus** [comment]
Ja, durch den Fehler wurde die Story mehrfach angelegt.
Ich schließe den Fehler, da an diesem an anderer Stelle gearbeitet wird
