### ISSUE TITLE
Die Menü-Sidebar blockiert den Hauptscreen

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#21]
Ich weiß nicht, ob das so soll, aber wenn ich oben rechts das Menü öffne, legt es sich über den Haupt-Content. Das sieht ein wenig ungewollt aus.
<img width="1241" alt="screen shot 2018-11-22 at 21 34 14" src="https://user-images.githubusercontent.com/32750106/48921211-75005680-ee9e-11e8-8ed4-83b4917c37c4.png">

**Comment by thetathaurus** [comment]
Dies ist gewollt. Ein klassisches Hover- Menu wie auch z.B. hier bei GitHub.
Dadurch wird vermieden, dass durch Menu-Einblendung der eigentliche Content scrollt, bzw. sich verschiebt, da der verfügbare Platz für den Content kleiner wird.
