### ISSUE TITLE
Autoren erstellen?

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#22]
Kann ich an anderer Stelle als auf der Home-Seite, ganz unten, neue Autoren hinzufügen?

**Comment by thetathaurus** [comment]
ja, in der Gesamtübersicht deiner Autoren.
Wo würde das Hinzufügen von Autoren deiner Meinung nach hilfreich sein?

**Comment by boxerfred** [comment]
Ich fände es im Menü rechts oben, das kommt, wenn ich die Grafik anklicke, sinnvoll. Vielleicht eine schnelle Verlinkung auf "Manage my authors"?

**Comment by thetathaurus** [comment]
In Release 0.4.1 implementiert
