### ISSUE TITLE
Autorenerstellung: Bild abgeschnitten

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#23]
Wenn ich ein hochformatiges Bild hochlade, ist es oben abgeschnitten: 

<img width="1243" alt="screen shot 2018-11-22 at 21 43 43" src="https://user-images.githubusercontent.com/32750106/48921388-c0ffcb00-ee9f-11e8-96a4-7ede939b91b0.png">

**Comment by thetathaurus** [comment]
Ist ein Fehler. Mit dem Format - Control ist vorgesehen, dass man Steuern kann ob ein Bild flächig oder füllend angezeigt werden kann. Das Control zieht aber aktuell nicht bei der Darstellung. Wird behoben. Der Default für Avatare wird "contain" sein

**Comment by thetathaurus** [comment]
implemented and released in v.0.3.3

**Comment by boxerfred** [comment]
Im Edit-Modus eines Autors ist das Bild immer noch abgeschnitten.

<img width="1280" alt="screen shot 2018-12-04 at 20 25 07" src="https://user-images.githubusercontent.com/32750106/49467418-bed42f80-f802-11e8-9f74-cd4731a738dc.png">
