### ISSUE TITLE
Das Switchen von "Cover" zu "Contain" und vice versa hat keinen Effekt

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#25]
<img width="1178" alt="screen shot 2018-12-04 at 20 26 15" src="https://user-images.githubusercontent.com/32750106/49467508-f17e2800-f802-11e8-8c9a-93ecd33730a1.png">

Außerdem passiert auch nichts, wenn ich die Änderung speichere. Liegt das an meinem Bild oder ist das ein Bug?

**Comment by thetathaurus** [comment]
Löse dich Mal von den Image Darstellungen von Avatare und Bildern. Der
Fehler ist im nächsten Release behoben

**Comment by boxerfred** [comment]
Ich gehe ohne echte Struktur durch. Ich hoffe, das ist für dich okay. Wenn du dir eine andere Herangehensweise wünschst, sag mir, wie du es dir vorstellst, oder welche Informationen du möchtest/brauchst, um das Feedback wertig verarbeiten zu können.

**Comment by thetathaurus** [comment]
*g* kein Problem. Da es aber das 3. Ticket in Richtung "Bild wird nicht richtig angezeigt war", wollte ich dir unnötige Schreibarbeit ersparen. Alle Feedbacks werden analysiert und wenn möglich in guten Code umgewandelt.

In Release 0.4.1 implementiert
