### ISSUE TITLE
Quotes werden in der Autorenbeschreibung nicht dargestellt

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#26]
<img width="762" alt="screen shot 2018-12-04 at 20 29 50" src="https://user-images.githubusercontent.com/32750106/49467737-66516200-f803-11e8-9c19-40b7b0a3c01c.png">
<img width="862" alt="screen shot 2018-12-04 at 20 29 45" src="https://user-images.githubusercontent.com/32750106/49467738-66516200-f803-11e8-9e18-dba4ee8b1b83.png">

Ich hab in der Edit-Maske die Beschreibung geändert, konnte auch abspeichern, aber das Resultat siehst du ja.

**Comment by boxerfred** [comment]
Alles andere funktioniert korrekt.

**Comment by thetathaurus** [comment]
Danke für das Feedback. Wird korrigiert.

**Comment by thetathaurus** [comment]
ist in version 0.4.1 korrigiert
