### ISSUE TITLE
In die Autorenbeschreibung eingefügte Bilder skalieren nicht

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#27]
Das eingefügte Bild bleibt in der Originalgröße

<img width="1271" alt="screen shot 2018-12-04 at 20 32 22" src="https://user-images.githubusercontent.com/32750106/49467903-cc3de980-f803-11e8-850a-9915c1daae3a.png">

**Comment by boxerfred** [comment]
Ich habs mit einem kleineren Bild probiert, das sprengt aber auch die Box.

**Comment by thetathaurus** [comment]
Das eingefügte Bild kann im Edit-Modus der Größe nach angepasst werden.

Oder referenzierst du darauf, dass das Bild bei Verkleinerung des Screens nicht responsive skaliert?

**Comment by boxerfred** [comment]
Auf das mangelnde responsive skalieren. Wenn ich ein Bild zu groß einstelle, legt es sich über das Autorenbild auf der rechten Seite.

**Comment by thetathaurus** [comment]
In Ordnung. Dann ist es ein Enhancement ;-)
Sehe ich genau so

**Comment by thetathaurus** [comment]
ist in Version 0.4.2 behoben
