### ISSUE TITLE
Meine Story wird nicht unter der Autorenseite angezeigt

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#28]
Siehe Bild: 

<img width="595" alt="screen shot 2018-12-04 at 20 35 09" src="https://user-images.githubusercontent.com/32750106/49468056-23dc5500-f804-11e8-9c29-708cf0904fb9.png">

**Comment by boxerfred** [comment]
Vanion ist allerdings nur Contributor. Autor der Story ist Lukas.

**Comment by thetathaurus** [comment]
ist ein Fehler, wird korrigiert

**Comment by boxerfred** [comment]
Wird es eine Unterscheidung zwischen "Stories" und "Contributions" geben?

**Comment by thetathaurus** [comment]
ja für die Bessere Einordnung des Authors

**Comment by thetathaurus** [comment]
ist in version 0.4.1 behoben
