### ISSUE TITLE
Erneutes Bookmarken bringt mich zur Story

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#32]
Meine Erwartung wäre, dass ich damit mein Bookmark wieder entfernen kann. 

<img width="883" alt="screen shot 2018-12-04 at 20 41 32" src="https://user-images.githubusercontent.com/32750106/49468388-0d82c900-f805-11e8-9380-f0d8698271ed.png">

**Comment by thetathaurus** [comment]
danke für das super feedback. 
Tatsächlich war die Intention, dass der Bookmark dich, wenn gesetzt zu der Stelle bringt, aber ich bin auch schon ein paar mal darüber gestolpert. Werde mit click auf den Bookmark diesen entfernen

**Comment by thetathaurus** [comment]
ist in release 0.4.1 implementiert
