### ISSUE TITLE
Ich kann Stories löschen, wo ich nur Contributor bin

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#33]
<img width="1148" alt="screen shot 2018-12-04 at 20 44 14" src="https://user-images.githubusercontent.com/32750106/49468523-681c2500-f805-11e8-8ce9-e020e67a3e34.png">

(Es kann sein, dass du mich bei dieser Story als Eigentümer eingetragen hast? Aber als Autor ist "Wulfgar" hinterlegt)

**Comment by thetathaurus** [comment]
Du hattest "Master" Rechte, was dir Lösch-Rechte ermöglicht.
Co-Authoren haben die selben Rechte wie ein Owner.

Werde das Löschen durch eine Master deaktiveren, da dies nicht sinnvoll ist.

**Comment by thetathaurus** [comment]
Problem in Release 0.4.1 behoben
