### ISSUE TITLE
Beim Upload eines Profilbilds muss ich nicht versichern, dass ich die Rechte daran habe

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#34]
Überall sonst muss ich das.

**Comment by thetathaurus** [comment]
Das versichern, dass du die Rechte hast wird im Release 0.4.1 vollständig entfernt und ggf mit einem nachträglichen Dialog abgesichert. Die Click-Folge (erst versichern, dann auswählen) entspricht nicht der gängigen Ordnung der Aktionen und verbraucht unnötig Platz auf kleinen Displays.

**Comment by boxerfred** [comment]
Supi.
