### ISSUE TITLE
Beim neuen Hinzufügen eines Bookmarks hat sich die Seite komplett neu geladen?

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#36]
Der ist tricky:

Ich hab storylike.com aufgerufen und habe dann sofort auf ein noch nicht angewähltes Bookmark geklickt. Daraufhin hat sich die Seite komplett neu geladen, der Bookmark war dann korrekt hinterlegt. Alle weiteren Bookmarks, die ich angeklickt habe, haben nicht zu einem Neuladen der Seite geführt, und ich hab's bisher nicht nochmal nachvollziehen können.

**Comment by thetathaurus** [comment]
Ich konnte es nicht nachstellen, habe aber eine leichte Abweichung in der Implementierung gedreht.
Ich markiere es einmal als gelöst, packe aber einen review-tag drauf.

ist in version 0.4.2 korrigiert
