### ISSUE TITLE
Wenn ich eine Geschichte editiere, sehe ich nicht, wer da als Autor eingetragen ist

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#37]
![screenshot 2018-12-20 at 11 55 28](https://user-images.githubusercontent.com/32750106/50280933-2b2f6f80-044e-11e9-916f-47088e4acabc.png)

Ich kann mit dem Bild des Autors nicht interagieren, wenn kein Bild hinterlegt ist, weiß ich nicht, wer da eingetragen ist.

**Comment by boxerfred** [comment]
(Was doof ist, weil ich den ja löschen könnte)

**Comment by thetathaurus** [comment]
ist in version 0.4.2 durch einen zusätzlichen Tooltip implementiert
