### ISSUE TITLE
In der Geschichtsübersicht erkenne ich den Autor nicht, wenn kein Bild hinterlegt ist

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#38]
Vorschlag: wenn ich über den Autor hovere, bekomme ich einige Informationen wie den Namen angezeigt? Ansonsten müsste ich erst den Autor anklicken und mich aus der Geschichte herausbewegen. 

![screenshot 2018-12-20 at 11 56 25](https://user-images.githubusercontent.com/32750106/50280982-603bc200-044e-11e9-973d-76c25b6e75e5.png)

**Comment by thetathaurus** [comment]
Zusätzliches hover - element mit Namen wurde in Version 0.4.2 hinzugefügt
