### ISSUE TITLE
Aufruf der Story 325

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#39]
Ich kann die Story 325 (https://www.storylike.com/story/325) nicht über den Catalog finden. Ich bin aber als Contributor eingetragen. 

Ich kann also über meine Autorenseite auf die Geschichte navigieren: 

![screenshot 2018-12-20 at 11 59 15](https://user-images.githubusercontent.com/32750106/50281093-b14bb600-044e-11e9-8e35-dc9b1df5372a.png)

Auf meiner Autorenseite sehe ich Informationen wie Geschichtstitel, Autor, Bild etc. - wenn ich dann aber auf die Geschichte klicke, sehe ich nur einen Bruchteil dieser Informationen: 

![screenshot 2018-12-20 at 12 00 18](https://user-images.githubusercontent.com/32750106/50281152-d93b1980-044e-11e9-96c5-f208cddad6ae.png)

**Comment by thetathaurus** [comment]
ist ein fehler., wurde in 0.4.2 behoben
