### ISSUE TITLE
Endloss-Scrolling 

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#4]
"Wenn ich eine Weile im Endlos-Scrolling lese, und wieder hoch will, muss ich echt hart scrollen
oder die Map nutzen. Wie wäre ein ""Back to top""/""Back to last block""-Button?"

**Comment by thetathaurus** [comment]
Ich werde prüfen, wie sich ein Button im oberen Bereich anfühlt, wenn im
Mobile-Modus der Header ausgeblendet wird.

**Comment by thetathaurus** [comment]
Die Keyboard-Shortcuts unterstützen jetzt eine Navigation mit den Pfeiltasten (Blockweises voranschreiten)
Aktuell ist der Nutzwert des eines einzelnen Buttons im oberen Bereich eher gering. Für die Navigation ist aktuell die Map vorgesehen. 

Falls weitere Anfragen hierzu kommen, wird das Konzept nochmal ausgepackt
