### ISSUE TITLE
Wiki: Die Suche ist case sensitive

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#41]
Wenn ich nach einer bestimmten Wiki suche, muss ich Groß- und Kleinschreibung beachten.

"breaki" führt nicht dazu, dass ich wie erwartet "Breaking Bad" finden würde. Ich muss "Breaki" schreiben.

![screenshot 2018-12-20 at 12 04 36](https://user-images.githubusercontent.com/32750106/50281365-83b33c80-044f-11e9-8576-82e73ca77e7b.png)
![screenshot 2018-12-20 at 12 04 19](https://user-images.githubusercontent.com/32750106/50281366-844bd300-044f-11e9-9e8f-4abd6406eca0.png)

**Comment by thetathaurus** [comment]
Fehler wurde in version 0.4.2 behoben
