### ISSUE TITLE
Wiki: Entfernen des Suchbegriffs setzt die Suche nicht zurück

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#42]
Wenn ich den Suchbegriff via Drücken der "x"-Schaltfläche zurücksetze, wäre meine Erwartung, dass dann auch alle Register/Wikis wieder angezeigt werden. Stattdessen passiert aber nichts, nur der Text wird gelöscht. 

![screenshot 2018-12-20 at 12 06 04](https://user-images.githubusercontent.com/32750106/50281429-b65d3500-044f-11e9-97fc-8e805b2f4a5a.png)
![screenshot 2018-12-20 at 12 06 10](https://user-images.githubusercontent.com/32750106/50281430-b65d3500-044f-11e9-8ed9-c59144d30be4.png)

Das verhält sich konträr dazu, wenn ich meinen Suchbegriff via Backspace/Del entferne: dann werden mir nämlich alle Register wieder angezeigt.

**Comment by thetathaurus** [comment]
Fehler wurde in 0.4.2 behoben
