### ISSUE TITLE
Feature Request: Register einklappbar machen?

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#43]
Vorschlag: in der Wiki-Übersicht könnten Register-Kategorien, bspw. "TV", einklappbar sein, um ewiges Scrollen zu vermeiden.

**Comment by thetathaurus** [comment]
Der Catalog vom Wikis ist derzeit ein Provisorium.
Für eine Suche ist ein Filter / Input basierte 

In welchen Situationen hast du "ewig" gescrollt? Beim Suchen oder um einen Überblick zu bekommen?
