### ISSUE TITLE
Falscher Fokus bei Register-Öffnung

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#6]
"Wenn ich einen Hint (bpsw. ""Elias"") anklicke, öffnet sich der Register von der Seite im falschen Fokus, 
der größte Teil ist ausgeblendet, siehe Bild"

https://i.imgur.com/svVBQXn.png

**Comment by thetathaurus** [comment]
ist ein Fehler, wird korrigiert

**Comment by thetathaurus** [comment]
Tritt aktuell nur beim ersten klicken auf. Warum ist noch unbekannt ;-)

**Comment by thetathaurus** [comment]
v.0.5.2
