### ISSUE TITLE
Bild-Fokus bei Register-Öffnung in Geschichte

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#7]
"Ich hab ""Elias"" angeklickt, dann auf das hinterlegte Bild geklickt, und das Ergebnis ist nicht so cool, 
siehe Bild"

https://i.imgur.com/Yb1LEWP.jpg

**Comment by thetathaurus** [comment]
*g* konzentration auf das wesentliche. Ich prüfe eine Alternative

**Comment by thetathaurus** [comment]
implemented and released in v.0.3.3
