### ISSUE TITLE
Beschreibung der Zugangslevel umständlich

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#89]
<img width="482" alt="screenshot 2019-01-10 at 22 40 45" src="https://user-images.githubusercontent.com/32750106/50998778-d0f36d00-1528-11e9-90a9-6a38a0ad7441.png">

Sollte das nicht lieber "Only you/your authors can read and contribute to the story" heißen statt "only authors"?

**Comment by thetathaurus** [comment]
Ich habe es in "only you and co-authors can read and contribute." geändert.
Da es auch Autoren von anderen Accounts sein können, würde "Only you/your authors" nicht richtig sein.
Mit der Funktion kannst du anderen Personen verwaltende Rechte an der Story geben
