### ISSUE TITLE
Kannst du mir einen zweiten Account geben?

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#90]
Damit ich die Zugriffsrechte und die Contribution-Funktionalitäten testen kann? 

Wenn du unterschiedliche Emails brauchst: lukas@engonien.de, lukas.heinen@googlemail.com

**Comment by thetathaurus** [comment]
Nutze beim Login den "Login with Google" Button. Damit bekommst du einen 2. Account
