### ISSUE TITLE
Bei Access Level = Kiosk taucht ein Author direkt als Contributor auf

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#91]
<img width="963" alt="screenshot 2019-01-10 at 22 43 02" src="https://user-images.githubusercontent.com/32750106/50998891-22036100-1529-11e9-995b-0660497bb98a.png">

Ich kenne Artemis nicht, aber sie ist direkt eingetragen als Contributor? Aufgetreten bei der Erstellung einer Geschichte, vor dem Speichern.

**Comment by thetathaurus** [comment]
Ist ein Fehler meinerseits. Für eine Demo hatte ich Arthemis an deine Story gesetzt. Sorry ;-)
