### ISSUE TITLE
Geschichtenerstellung: Contributor-Suche kapott?

### ISSUE THREAD

**Issue by boxerfred** [thetathaurus/storylike#92]
Ich bin mir nicht sicher, wie genau ich das geschafft habe, aber als ich "Vanion" als Contributor hinzufügen wollte in einer neuen Geschichte (einer meiner Autoren), ist folgendes passiert: 

<img width="481" alt="screenshot 2019-01-10 at 22 44 58" src="https://user-images.githubusercontent.com/32750106/50998995-7575af00-1529-11e9-942e-2c4661b5058f.png">

**Comment by boxerfred** [comment]
Okay, die Autoren werden nicht korrekt geladen: 

<img width="465" alt="screenshot 2019-01-10 at 22 46 17" src="https://user-images.githubusercontent.com/32750106/50999051-95a56e00-1529-11e9-95b2-c19e3213693a.png">

**Comment by boxerfred** [comment]
Manchmal passiert auch gar nichts, und auch das Entfernen funktioniert nicht richtig.

**Comment by thetathaurus** [comment]
Funktion wurde überarbeitet. Das Control arbeitet jetzt wieder wie gewohnt
