### ISSUE TITLE
Schaltfläche "Textbearbeitung" - Fehler und Hinweise

### ISSUE THREAD

**Issue by Executer84** [thetathaurus/storylike#94]
Ein paar Hinweise zur Schaltfläche "Textbearbeitung":
1. Auf dem Deckblatt eines Buches funktionieren im Bereich "Cover text" 3 Knöpfe nicht. Quelle/Link, Datei Einfügen und Tx. Wenn ich einen normalen Abschnitt meines Buches schreibe funktionieren die.
2. Das "A" könnte man farbig hinterlegen. Mir war jetzt durch die allgemeine schwarz-weiß Ansicht nicht auf Anhieb klar, dass ich hier die Textfarbe ändern kann.
3. Geht es nur mir so, oder sind die Piktogramme für "Quelle/Link hinterlegen" und "Tx" nicht allgemein bekannt? Das ich mit den zwei Kettengliedern eine Quelle/ einen Link hinterlegen kann musste ich mir erst beibringen. Was "Tx" bedeutet ist mir offen gesagt immer noch nicht ganz klar. Text rücksetzen auf Standardformat? Man könnte hier die Benutzerfreundlichkeit verbessern. Erklärendes Popup bei allen Schaltflächen nach ca. 1sec?
![image](https://user-images.githubusercontent.com/46623291/51073165-0d2fe600-166d-11e9-8adb-400e08f9b89a.png)

**Comment by thetathaurus** [comment]
Die beiden Ketten sind das standard-Symbol für "verlinkungen". Die Symbole sind tatsächlich an Word orientiert. Tx bedeutet: Formatierung zurücksetzten. Aus Platzmangel und internationalität bekomme ich da keinen Text hin, maximal ein Tooltip. Hier wird es wohl eher auf "learning by doing" hinauslaufen ;-)
