### ISSUE TITLE
Beim Text editieren - Abbrechen Schaltfläche hinzufügen, "Abschnitt löschen" anders kennzeichnen + Sicherheitsabfrage

### ISSUE THREAD

**Issue by Executer84** [thetathaurus/storylike#96]
Einige Hinweise beim Editieren eines Textes:
1. Wenn ich einen Text editiere, gibt es keine "Abbrechen"-Funktion. Der alte, ursprüngliche Text geht also immer zwangsweise verloren, sobald ich anfange etwas zu ändern / zu überschreiben. Hier empfehle ich dringend eine backup-Funktion. Alten Text zwischenspeichern und bei Bedarf mit "Abbrechen" wiederherstellen.
2. Ein "x" ist standardmäßig als "Schließen" definiert und nicht unbedingt als "löschen"! Die Schaltfläche, mit der ein Abschnitt komplett gelöscht wird, sollte besser gekennzeichnet sein. Nach meiner Meinung sogar mit Sicherheitsabfrage (die man in den persönlichen Einstellungen dann evtl. nach Wunsch und auf eigenes Risiko abschalten kann)! Es ist sehr ärgerlich, wenn ich 20 Seiten Text mit einem Klick versehentlich lösche.

-> Ich empfehle insgesamt 4 Schaltflächen: "Publish", "Preview", "Cancel/Abort" und "Delete"
![image](https://user-images.githubusercontent.com/46623291/51111423-54001600-17fc-11e9-9e98-fa6e8815919c.png)

**Comment by thetathaurus** [comment]
Aktuell ist hier ein fehlerhaftes Verhalten, jedoch kommt die Sicherheitsabfrage nicht wie erwartet ;-(
Die Funktionalität ist exakt so vorgesehen, nur mit einem Button implementiert. 
Darüber hinaus ist eine Versionierung vorhanden, nur noch nicht über die UI einsehbar

**Comment by thetathaurus** [comment]
Das Problem war ein bisschen kniffliger als gedacht, ist aber jetzt gelöst.
Es gibt etwa 12 Szenarien und Situation die ein Zusammenspiel und Zusammenfassung nicht einfach machen.
Das Verhalten wurde geändert, dass wenn man auf "Cancel" drückt, wird man immer gefragt, es sei denn der Text ist leer und war schon immer leer (aus versehen einen block angelegt und sofort wieder gecancelt). 
Das ein Block direkt gelöscht wurde, lag an einer falschen Versionierung die nun behoben ist.
